name: forager spirit
favicon: null
layout_spectrum: 0.91187
typography_spectrum: 0.09243
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: FORAGER spirit
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#c1272d'
    - '#bf242a'
    - '#c1262c'
    - '#c1262c'
  brandStrength: 0.0625
  lightness: 0.6875
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
