favicon: null
name: foragerspirit
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.3884748925920576
  brandStrength: 1
  lightness: 0.1043434462044388
  brandColors:
    - '#E3DFD6'
    - '#501E0D'
    - '#A58B3B'
    - '#C90510'
    - '#FD6058'
  rhythmicContrast: 0.2061018159147352
typography_spectrum: 0.4913321908097714
layout_spectrum: 0.2538261855952442
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
