name: foragerspirit
favicon: null
layout_spectrum: 0.25382618559524417
typography_spectrum: 0.4913321908097714
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.528854220174253
  lightness: 0.1043434462044388
  saturation: 0.3884748925920576
  rhythmicContrast: 0.2061018159147352
purpose: []
